name: Subsplit Libraries

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  subsplit:
    name: Split Packages (${{ matrix.package.local_path }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          # Bridges
          - local_path: 'bridge/http-bridge'
            split_repository: 'http-bridge'
          - local_path: 'bridge/symfony-http-bridge'
            split_repository: 'symfony-http-bridge'
          - local_path: 'bridge/laravel-http-bridge'
            split_repository: 'laravel-http-bridge'
          - local_path: 'bridge/psr-http-bridge'
            split_repository: 'psr-http-bridge'
          # Components
          - local_path: 'component/compiler'
            split_repository: 'compiler'
          - local_path: 'component/cpu-info'
            split_repository: 'cpu-info'
          - local_path: 'component/globals-provider'
            split_repository: 'globals-provider'
          - local_path: 'component/runtime'
            split_repository: 'runtime'
          - local_path: 'component/http'
            split_repository: 'http'
          - local_path: 'component/http-body-decoder'
            split_repository: 'http-body-decoder'
          - local_path: 'component/http-static-provider'
            split_repository: 'http-static-provider'
          - local_path: 'component/os-info'
            split_repository: 'os-info'
          - local_path: 'component/weak-types'
            split_repository: 'weak-types'
          # Contracts
          - local_path: 'contracts/http-contracts'
            split_repository: 'http-contracts'
    steps:
      - uses: actions/checkout@v4

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package.split_repository }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: "master"
          package_directory: 'libs/${{ matrix.package.local_path }}'
          repository_organization: 'boson-php'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "SerafimArts"
          user_email: "nesk@xakep.ru"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          branch: "master"
          package_directory: 'libs/${{ matrix.package.local_path }}'
          repository_organization: 'boson-php'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "SerafimArts"
          user_email: "nesk@xakep.ru"
